export type TabType = "news" | "cartoon" | "games";

export const content: Record<TabType, string[]> = {
  news: [
    "Breaking: React 19 Released!",
    "Vite 5.0 now supports faster HMR",
    "Tailwind CSS introduces new animations",
  ],
  cartoon: [
    "Mickey Mouse Adventures",
    "Tom & Jerry Classics",
    "SpongeBob SquarePants",
  ],
  games: ["Chess", "Ludo", "Tic-Tac-Toe"],
};
export const Contributor = [
  {
    id: 6,
    name: "Geet Srivastava",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "Figma Expert",
    joinDate: "Sep 2025",
    specialties: ["Figma", "Java", "Backend"],
    isTopContributor: false,
    from: 'BBD University'
  },
  {
    id: 7,
    name: "Pranjal Gupta",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "AI & ML",
    joinDate: "Oct 2025",
    specialties: ["C", "Python", "Tkinter"],
    isTopContributor: false,
    from: 'BBD University'
  },
  {
    id: 8,
    name: "Akshara Dixit",
    avatar:
      "https://res.cloudinary.com/doytvgisa/image/upload/v1758643144/Geet_y3etiz.jpg",
    contributions: 10,
    role: "Web Development",
    joinDate: "Oct 2025",
    specialties: ["C", "Problem Solving"],
    isTopContributor: false,
    from: 'BBD University'
  },

]

export const companies = [
  {
    "id": 1,
    "company_name": "Google",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Python", "System Design", "Data Structures"],
    "experience_required": "0-2 years",
    "package_lpa": 18.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 2,
    "company_name": "Microsoft",
    "industry": "Technology",
    "location": "Hyderabad, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["C++", "Azure", "Cloud Computing", "Algorithms"],
    "experience_required": "0-2 years",
    "package_lpa": 19.2,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 3,
    "company_name": "Amazon",
    "industry": "E-commerce & Technology",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer I",
    "required_skills": ["Java", "AWS", "Distributed Systems", "OOP"],
    "experience_required": "0-1 years",
    "package_lpa": 17.8,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2024-2025 Batch"
  },
  {
    "id": 4,
    "company_name": "Flipkart",
    "industry": "E-commerce",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Microservices", "SQL"],
    "experience_required": "0-2 years",
    "package_lpa": 15.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 5,
    "company_name": "TCS",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Assistant Systems Engineer",
    "required_skills": ["Programming Basics", "Problem Solving", "Communication"],
    "experience_required": "0 years",
    "package_lpa": 3.6,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA/M.Sc.",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 6,
    "company_name": "Infosys",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Systems Engineer",
    "required_skills": ["Programming", "Database", "Communication"],
    "experience_required": "0 years",
    "package_lpa": 3.8,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/M.E./M.Tech/MCA/M.Sc.",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 7,
    "company_name": "Wipro",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Project Engineer",
    "required_skills": ["Java", "SQL", "Basic Programming"],
    "experience_required": "0 years",
    "package_lpa": 3.5,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/M.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 8,
    "company_name": "Accenture",
    "industry": "Consulting & IT Services",
    "location": "Multiple Locations",
    "job_role": "Application Development Associate",
    "required_skills": ["Programming", "Analytical Skills", "Communication"],
    "experience_required": "0 years",
    "package_lpa": 4.5,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/M.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 9,
    "company_name": "Cognizant",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Programmer Analyst Trainee",
    "required_skills": ["Programming", "SQL", "Problem Solving"],
    "experience_required": "0 years",
    "package_lpa": 4.0,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 10,
    "company_name": "Capgemini",
    "industry": "Consulting & IT Services",
    "location": "Multiple Locations",
    "job_role": "Analyst",
    "required_skills": ["Programming", "Database", "Communication"],
    "experience_required": "0 years",
    "package_lpa": 4.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 11,
    "company_name": "Goldman Sachs",
    "industry": "Financial Services",
    "location": "Bangalore, India",
    "job_role": "Analyst - Software Engineering",
    "required_skills": ["Java", "C++", "Data Structures", "Financial Markets"],
    "experience_required": "0-1 years",
    "package_lpa": 22.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 12,
    "company_name": "Morgan Stanley",
    "industry": "Financial Services",
    "location": "Mumbai, India",
    "job_role": "Technology Analyst",
    "required_skills": ["Java", "Python", "SQL", "Financial Knowledge"],
    "experience_required": "0-1 years",
    "package_lpa": 20.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 13,
    "company_name": "Deutsche Bank",
    "industry": "Financial Services",
    "location": "Pune, India",
    "job_role": "Technology Analyst",
    "required_skills": ["Java", "Spring", "SQL", "Agile"],
    "experience_required": "0-1 years",
    "package_lpa": 18.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 14,
    "company_name": "Walmart",
    "industry": "Retail & Technology",
    "location": "Bangalore, India",
    "job_role": "Software Engineer II",
    "required_skills": ["Java", "React", "Microservices", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 16.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 15,
    "company_name": "Adobe",
    "industry": "Software",
    "location": "Noida, India",
    "job_role": "Computer Scientist",
    "required_skills": ["C++", "Algorithms", "Graphics", "Design Patterns"],
    "experience_required": "0-1 years",
    "package_lpa": 20.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 16,
    "company_name": "Oracle",
    "industry": "Technology",
    "location": "Bangalore, India",
    "job_role": "Software Developer",
    "required_skills": ["Java", "SQL", "PL/SQL", "Database"],
    "experience_required": "0-2 years",
    "package_lpa": 12.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 17,
    "company_name": "SAP Labs",
    "industry": "Enterprise Software",
    "location": "Bangalore, India",
    "job_role": "Developer Associate",
    "required_skills": ["Java", "SAP HANA", "Cloud", "Database"],
    "experience_required": "0-1 years",
    "package_lpa": 13.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 18,
    "company_name": "Intel",
    "industry": "Semiconductor",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["C", "C++", "Embedded Systems", "Linux"],
    "experience_required": "0-1 years",
    "package_lpa": 14.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 19,
    "company_name": "Qualcomm",
    "industry": "Semiconductor & Telecom",
    "location": "Hyderabad, India",
    "job_role": "Engineer",
    "required_skills": ["C", "C++", "Embedded C", "Wireless Tech"],
    "experience_required": "0-1 years",
    "package_lpa": 15.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in ECE/CSE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 20,
    "company_name": "Nvidia",
    "industry": "Graphics & AI",
    "location": "Pune, India",
    "job_role": "Software Engineer",
    "required_skills": ["C++", "CUDA", "GPU Programming", "Computer Graphics"],
    "experience_required": "0-1 years",
    "package_lpa": 21.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 21,
    "company_name": "Cisco",
    "industry": "Networking",
    "location": "Bangalore, India",
    "job_role": "Software Engineer I",
    "required_skills": ["C", "Python", "Networking", "Linux"],
    "experience_required": "0-2 years",
    "package_lpa": 13.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 22,
    "company_name": "VMware",
    "industry": "Cloud & Virtualization",
    "location": "Bangalore, India",
    "job_role": "Member of Technical Staff",
    "required_skills": ["C++", "Java", "Virtualization", "Cloud"],
    "experience_required": "0-1 years",
    "package_lpa": 17.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 23,
    "company_name": "Salesforce",
    "industry": "Cloud & CRM",
    "location": "Hyderabad, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Salesforce", "Cloud", "Apex"],
    "experience_required": "0-1 years",
    "package_lpa": 16.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 24,
    "company_name": "Intuit",
    "industry": "Financial Software",
    "location": "Bangalore, India",
    "job_role": "Software Engineer 1",
    "required_skills": ["Java", "Spring Boot", "React", "Microservices"],
    "experience_required": "0-1 years",
    "package_lpa": 18.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 25,
    "company_name": "PayPal",
    "industry": "Fintech",
    "location": "Chennai, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Node.js", "Payment Systems", "Security"],
    "experience_required": "0-2 years",
    "package_lpa": 17.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 26,
    "company_name": "Paytm",
    "industry": "Fintech",
    "location": "Noida, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Android", "Backend", "APIs"],
    "experience_required": "0-2 years",
    "package_lpa": 10.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 27,
    "company_name": "PhonePe",
    "industry": "Fintech",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Kotlin", "Microservices", "Distributed Systems"],
    "experience_required": "0-2 years",
    "package_lpa": 15.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 28,
    "company_name": "Razorpay",
    "industry": "Fintech",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Go", "Payment Gateway", "APIs"],
    "experience_required": "0-2 years",
    "package_lpa": 14.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 29,
    "company_name": "Zomato",
    "industry": "Food Tech",
    "location": "Gurgaon, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Django", "Microservices", "SQL"],
    "experience_required": "0-2 years",
    "package_lpa": 12.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 30,
    "company_name": "Swiggy",
    "industry": "Food Tech",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Kafka", "Redis"],
    "experience_required": "0-2 years",
    "package_lpa": 13.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 31,
    "company_name": "Ola",
    "industry": "Transportation Tech",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Node.js", "MongoDB", "Microservices"],
    "experience_required": "0-2 years",
    "package_lpa": 11.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 32,
    "company_name": "Uber",
    "industry": "Transportation Tech",
    "location": "Bangalore, India",
    "job_role": "Software Engineer I",
    "required_skills": ["Go", "Java", "Distributed Systems", "Kafka"],
    "experience_required": "0-2 years",
    "package_lpa": 19.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 33,
    "company_name": "OYO",
    "industry": "Hospitality Tech",
    "location": "Gurgaon, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Java", "AWS", "Microservices"],
    "experience_required": "0-2 years",
    "package_lpa": 10.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 34,
    "company_name": "MakeMyTrip",
    "industry": "Travel Tech",
    "location": "Gurgaon, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Spring", "React", "MongoDB"],
    "experience_required": "0-2 years",
    "package_lpa": 9.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 35,
    "company_name": "BookMyShow",
    "industry": "Entertainment Tech",
    "location": "Mumbai, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Python", "AWS", "Microservices"],
    "experience_required": "0-2 years",
    "package_lpa": 11.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 36,
    "company_name": "Byju's",
    "industry": "EdTech",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["React", "Node.js", "MongoDB", "AWS"],
    "experience_required": "0-2 years",
    "package_lpa": 8.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 37,
    "company_name": "Unacademy",
    "industry": "EdTech",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Python", "Django", "React", "PostgreSQL"],
    "experience_required": "0-2 years",
    "package_lpa": 10.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 38,
    "company_name": "Vedantu",
    "industry": "EdTech",
    "location": "Bangalore, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "React", "WebRTC", "AWS"],
    "experience_required": "0-2 years",
    "package_lpa": 9.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 39,
    "company_name": "Meesho",
    "industry": "E-commerce",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "Spring Boot", "Kafka", "Redis"],
    "experience_required": "0-2 years",
    "package_lpa": 14.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 40,
    "company_name": "Myntra",
    "industry": "Fashion E-commerce",
    "location": "Bangalore, India",
    "job_role": "Software Development Engineer",
    "required_skills": ["Java", "React", "Microservices", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 13.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 41,
    "company_name": "Nykaa",
    "industry": "Beauty E-commerce",
    "location": "Mumbai, India",
    "job_role": "Software Engineer",
    "required_skills": ["Python", "Django", "React", "AWS"],
    "experience_required": "0-2 years",
    "package_lpa": 10.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 42,
    "company_name": "Snapdeal",
    "industry": "E-commerce",
    "location": "Gurgaon, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Spring", "SQL", "NoSQL"],
    "experience_required": "0-2 years",
    "package_lpa": 8.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 43,
    "company_name": "Jio",
    "industry": "Telecom",
    "location": "Mumbai, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "Python", "Networking", "Cloud"],
    "experience_required": "0-2 years",
    "package_lpa": 7.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 44,
    "company_name": "Airtel",
    "industry": "Telecom",
    "location": "Gurgaon, India",
    "job_role": "Software Developer",
    "required_skills": ["Java", "Python", "Telecom Protocols", "OSS/BSS"],
    "experience_required": "0-2 years",
    "package_lpa": 6.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 45,
    "company_name": "Vodafone Idea",
    "industry": "Telecom",
    "location": "Pune, India",
    "job_role": "Engineer - IT",
    "required_skills": ["Java", "SQL", "Networking", "Linux"],
    "experience_required": "0-2 years",
    "package_lpa": 5.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT/ECE",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 46,
    "company_name": "HCL Technologies",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Graduate Engineer Trainee",
    "required_skills": ["Programming", "Database", "Communication"],
    "experience_required": "0 years",
    "package_lpa": 3.8,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 47,
    "company_name": "Tech Mahindra",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Associate Software Engineer",
    "required_skills": ["Java", "Python", "SQL"],
    "experience_required": "0 years",
    "package_lpa": 3.7,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 48,
    "company_name": "LTIMindtree",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Graduate Engineer Trainee",
    "required_skills": ["Programming", "Problem Solving", "Analytics"],
    "experience_required": "0 years",
    "package_lpa": 4.2,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./M.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 49,
    "company_name": "Mphasis",
    "industry": "IT Services",
    "location": "Bangalore, India",
    "job_role": "Associate Software Engineer",
    "required_skills": ["Java", "SQL", "Web Technologies"],
    "experience_required": "0 years",
    "package_lpa": 4.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 50,
    "company_name": "Persistent Systems",
    "industry": "IT Services",
    "location": "Pune, India",
    "job_role": "Software Engineer",
    "required_skills": ["Java", "C++", "Data Structures", "Algorithms"],
    "experience_required": "0-1 years",
    "package_lpa": 5.5,
    "job_type": "Full-time",
    "education": "B.Tech/B.E. in CSE/IT",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 51,
    "company_name": "Mindtree",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Digital Engineer",
    "required_skills": ["Programming", "Cloud", "Agile"],
    "experience_required": "0 years",
    "package_lpa": 4.1,
    "job_type": "Full-time",
    "education": "B.E./B.Tech/M.Tech/MCA",
    "hiring_for": "2025 Batch"
  },
  {
    "id": 52,
    "company_name": "L&T Infotech",
    "industry": "IT Services",
    "location": "Multiple Locations",
    "job_role": "Graduate Engineer Trainee",
    "required_skills": ["Programming", "Database", "Web Dev"],
    "experience_required": "0 years",
    "package_lpa": 4.0,
    "job_type": "Full-time",
    "education": "B.Tech/B.E./MCA",
    "hiring_for": "2025 Batch"
  }]